{{- if .Values.webhook.enabled }}
{{- if not .Values.certificates.certManager.enabled }}
---
# Simple approach: Use Kubernetes service CA
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smart-scheduler.fullname" . }}-webhook-server-cert
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/serving-cert-secret-name: {{ include "smart-scheduler.fullname" . }}-webhook-server-cert
type: kubernetes.io/tls
data:
  # This will be populated automatically by service-ca-operator (if available)
  # or we'll generate a self-signed cert
{{- end }}
{{- end }} 