{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podplacementpolicies.smartscheduler.io
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
  annotations:
    {{- if not .Values.crds.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  group: smartscheduler.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
                  matchExpressions:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          type: array
                          items:
                            type: string
              strategy:
                type: object
                properties:
                  base:
                    type: integer
                  rules:
                    type: array
                    items:
                      type: object
                      properties:
                        weight:
                          type: integer
                        nodeSelector:
                          type: object
                          additionalProperties:
                            type: string
                        affinity:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: string
                              labelSelector:
                                type: object
                                additionalProperties:
                                  type: string
                              topologyKey:
                                type: string
                              requiredDuringScheduling:
                                type: boolean
                              weight:
                                type: integer
                        name:
                          type: string
                        description:
                          type: string
                  rebalancePolicy:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      driftThreshold:
                        type: number
                      checkInterval:
                        type: string
                      maxPodsPerRebalance:
                        type: integer
              enabled:
                type: boolean
              priority:
                type: integer
            required:
            - selector
            - strategy
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
              matchedDeployments:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    currentDrift:
                      type: number
                    lastApplied:
                      type: string
                      format: date-time
              statistics:
                type: object
                properties:
                  totalPodsManaged:
                    type: integer
                  averageDrift:
                    type: number
                  rebalanceCount:
                    type: integer
                  lastUpdated:
                    type: string
                    format: date-time
              lastRebalance:
                type: string
                format: date-time
              observedGeneration:
                type: integer
    additionalPrinterColumns:
    - name: Enabled
      type: boolean
      jsonPath: .spec.enabled
    - name: Priority
      type: integer
      jsonPath: .spec.priority
    - name: Matched Deployments
      type: integer
      jsonPath: .status.statistics.totalPodsManaged
    - name: Avg Drift
      type: string
      jsonPath: .status.statistics.averageDrift
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: podplacementpolicies
    singular: podplacementpolicy
    kind: PodPlacementPolicy
    shortNames:
    - ppp
{{- end }} 