{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smart-scheduler.serviceAccountName" . }}
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}

{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "smart-scheduler.fullname" . }}-manager-role
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
rules:
# Core resources for placement strategy management
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

# Deployment management for applying placement policies
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch

# SmartScheduler CRDs
{{- if .Values.features.crdPolicies }}
- apiGroups:
  - smartscheduler.io
  resources:
  - podplacementpolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - smartscheduler.io
  resources:
  - podplacementpolicies/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - smartscheduler.io
  resources:
  - podplacementpolicies/finalizers
  verbs:
  - update
{{- end }}

# Leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

# Admission webhook
{{- if .Values.webhook.enabled }}
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingadmissionconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
{{- end }}

{{- with .Values.rbac.additionalRules }}
{{- toYaml . | nindent 0 }}
{{- end }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "smart-scheduler.fullname" . }}-manager-rolebinding
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "smart-scheduler.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "smart-scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

{{- if .Values.webhook.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "smart-scheduler.fullname" . }}-proxy-role
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "smart-scheduler.fullname" . }}-proxy-rolebinding
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "smart-scheduler.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "smart-scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }} 