apiVersion: v1
kind: Service
metadata:
  name: smart-scheduler-webhook-service
  namespace: smart-scheduler-system
spec:
  ports:
  - name: webhook-server
    port: 443
    targetPort: 9443
  selector:
    app: smart-scheduler
    control-plane: controller-manager
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionWebhook
metadata:
  name: smart-scheduler-mutating-webhook
  annotations:
    cert-manager.io/inject-ca-from: smart-scheduler-system/smart-scheduler-serving-cert
spec:
  webhooks:
  - name: mpod.smart-scheduler.io
    clientConfig:
      service:
        name: smart-scheduler-webhook-service
        namespace: smart-scheduler-system
        path: "/mutate-v1-pod"
    rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
      - key: name
        operator: NotIn
        values: ["kube-system", "smart-scheduler-system", "cert-manager"] 